export const BUILD_STATUS = {
  BUILDING: 'BUILDING',
  FAILURE: 'FAILURE',
  PREPARING: 'PREPARING',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
} as const;

export const SUBBUILD_TYPES = {
  APP: 'APP',
  PRIVATE_APP: 'PRIVATE_APP',
  THEME: 'THEME',
  REACT_THEME: 'REACT_THEME',
  NO_SUBBUILDS: 'NO_SUBBUILDS',
} as const;

export const DEPLOYABLE_STATES = {
  DEPLOYABLE: 'DEPLOYABLE',
  DEPRECATED: 'DEPRECATED_APP_NON_SUBCOMPONENT',
};
