export const BUILD_STATUS = {
  BUILDING: 'BUILDING',
  FAILURE: 'FAILURE',
  PREPARING: 'PREPARING',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
} as const;

export const SUBBUILD_TYPES = {
  APP: 'APP',
  PRIVATE_APP: 'PRIVATE_APP',
  THEME: 'THEME',
  REACT_THEME: 'REACT_THEME',
  NO_SUBBUILDS: 'NO_SUBBUILDS',
} as const;

export const DEPLOYABLE_STATES = {
  DEPLOYABLE: 'DEPLOYABLE',
  DEPRECATED: 'DEPRECATED_APP_NON_SUBCOMPONENT',
};

export const COMPONENT_TYPES = {
  APP: 'APP',
  PRIVATE_APP: 'PRIVATE_APP',
  PUBLIC_APP: 'PUBLIC_APP',
  THEME: 'THEME',
  REACT_THEME: 'REACT_THEME',
} as const;

export const SUBCOMPONENT_TYPES = {
  APP_ID: 'APP_ID',
  PACKAGE_LOCK_FILE: 'PACKAGE_LOCK_FILE',
  CRM_CARD_V2: 'CRM_CARD_V2',
  CARD_V2: 'CARD_V2',
  SERVERLESS_PKG: 'SERVERLESS_PKG',
  SERVERLESS_ROUTE: 'SERVERLESS_ROUTE',
  SERVERLESS_FUNCTION: 'SERVERLESS_FUNCTION',
  APP_FUNCTION: 'APP_FUNCTION',
  AUTOMATION_ACTION: 'AUTOMATION_ACTION',
  REACT_EXTENSION: 'REACT_EXTENSION',
} as const;
