import {
  ENVIRONMENTS as __ENVIRONMENTS,
  ENVIRONMENT_VARIABLES as __ENVIRONMENT_VARIABLES,
} from './environments';
import {
  DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME as __DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME,
  HUBSPOT_CONFIGURATION_FOLDER as __HUBSPOT_CONFIGURATION_FOLDER,
  HUBSPOT_CONFIGURATION_FILE as __HUBSPOT_CONFIGURATION_FILE,
} from './config';

// Environment Variables
export const ENVIRONMENTS = __ENVIRONMENTS;
export const ENVIRONMENT_VARIABLES = __ENVIRONMENT_VARIABLES;

// Config Variables
export const DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME =
  __DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME;
export const HUBSPOT_CONFIGURATION_FOLDER = __HUBSPOT_CONFIGURATION_FOLDER;
export const HUBSPOT_CONFIGURATION_FILE = __HUBSPOT_CONFIGURATION_FILE;
