import { ENVIRONMENTS as __ENVIRONMENTS } from './environments';
import { DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME as __DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME } from './config';

export const ENVIRONMENTS = __ENVIRONMENTS;
export const DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME =
  __DEFAULT_HUBSPOT_CONFIG_YAML_FILE_NAME;
